//! Themes embedded from `themes/*.yaml` at compile time.

use crate::theme::schema::Theme;

// Defines `BUILTIN_THEMES`: (file stem, YAML source) pairs generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/theme_list.rs"));

fn parse(slug: &str, yaml: &str) -> Result<Theme, serde_yml::Error> {
    let mut theme: Theme = serde_yml::from_str(yaml)?;
    if theme.slug.is_empty() {
        theme.slug = slug.to_string();
    }
    Ok(theme)
}

/// Skips themes that fail to parse; `every_builtin_theme_parses` keeps that set empty.
pub(super) fn load_builtin_themes() -> Vec<Theme> {
    BUILTIN_THEMES
        .iter()
        .filter_map(|(slug, yaml)| parse(slug, yaml).ok())
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_builtin_theme_parses() {
        for (slug, yaml) in BUILTIN_THEMES {
            if let Err(err) = parse(slug, yaml) {
                panic!("themes/{slug}.yaml: {err}");
            }
        }
    }
}
