//! Auto-generated theme list.
//!
//! This file is populated by `build.rs` at compile time from the `themes/*.yaml`
//! directory. The `include!` macro pulls in a generated Rust file that defines
//! `BUILTIN_THEMES` — a static array of `(slug, yaml_string)` tuples. Each tuple
//! is deserialized into a [`Theme`] struct at runtime by [`load_builtin_themes`].

use crate::theme::schema::Theme;

// This `include!` brings in the `BUILTIN_THEMES` constant generated by build.rs.
// It expands to something like:
//   const BUILTIN_THEMES: &[(&str, &str)] = &[("dracula", "name: Dracula\n..."), ...];
include!(concat!(env!("OUT_DIR"), "/theme_list.rs"));

/// Deserialize all compiled-in YAML theme strings into `Theme` structs.
///
/// Themes whose YAML fails to parse are silently skipped (the `filter_map`
/// returns `None` for those). If a theme's YAML does not include a `slug` field,
/// the filename-derived slug from `build.rs` is used as a fallback.
pub fn load_builtin_themes() -> Vec<Theme> {
    BUILTIN_THEMES
        .iter()
        .filter_map(|(slug, yaml)| {
            let mut theme: Theme = serde_yml::from_str(yaml).ok()?;
            if theme.slug.is_empty() {
                theme.slug = slug.to_string();
            }
            Some(theme)
        })
        .collect()
}
